### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by LiuOcean** [favoyang/unity-addressable-importer#13]
Import this package into a project that already install addressable, it doesn't work.

I need delete all my addressable settings. Then delete addressable and this package.

Reimport this package, then update addressable to 1.3.8.

I test this on Mac with Unity 2019.2

**Comment by favoyang** [comment]
I tried unity 2019.2 and addressabels 1.3.8 with no issue. What exactly the "import error"? is it an compilation error, or just asset not get imported by rules you defined.

**Comment by LiuOcean** [comment]
My English is bad. Sorry.
Just asset not get imported.

My project is using Addressable, I defined some groups. When I import this package, asset can't get imported.

Delete Addressable, all addressable setting and this package. 

Reinstall this package, it can work.

**Comment by favoyang** [comment]
That's expected behaviour. The importer only works when you "import" assets. For asserts already imported, you need either re-import them, or use the [quick assets import feature](https://github.com/favoyang/unity-addressable-importer/blob/master/Documentation~/AddressableImporter.md#quick-assets-import).

Issue closed.
